"""Pydantic schemas for interview coaching — guides and quality scoring."""

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Interview guide
# ---------------------------------------------------------------------------


class InterviewGuideRequest(BaseModel):
    """Input parameters for generating an interview guide."""

    hypothesis: str
    target_persona: str
    existing_insights: str = ""


class InterviewGuideExtracted(BaseModel):
    """An interview guide generated by the LLM."""

    title: str = ""
    opening_questions: list[dict] = []
    deep_dive_questions: list[dict] = []
    validation_questions: list[dict] = []
    anti_patterns_to_avoid: list[str] = []
    success_criteria: str = ""


class InterviewGuideResponse(BaseModel):
    """Persisted interview guide returned via the API."""

    id: str
    project_id: str
    title: str
    opening_questions: list[dict]
    deep_dive_questions: list[dict]
    validation_questions: list[dict]
    anti_patterns_to_avoid: list[str]
    success_criteria: str
    created_at: str

    model_config = {"from_attributes": True}


# ---------------------------------------------------------------------------
# Quality scoring
# ---------------------------------------------------------------------------


class QualityScoreExtracted(BaseModel):
    """Quality assessment of an interview produced by the LLM."""

    overall_score: float = Field(default=0.0, ge=0.0, le=1.0)
    mom_test_compliance: float = Field(default=0.0, ge=0.0, le=1.0)
    question_quality: float = Field(default=0.0, ge=0.0, le=1.0)
    insight_depth: float = Field(default=0.0, ge=0.0, le=1.0)
    bias_score: float = Field(default=0.0, ge=0.0, le=1.0)
    leading_questions_found: list[dict] = []
    missed_opportunities: list[dict] = []
    strengths: list[str] = []
    suggestions: list[str] = []


class QualityScoreResponse(BaseModel):
    """Persisted quality score returned via the API."""

    id: str
    interview_id: str
    overall_score: float
    mom_test_compliance: float
    question_quality: float
    insight_depth: float
    bias_score: float
    leading_questions_found: list[dict]
    missed_opportunities: list[dict]
    strengths: list[str]
    suggestions: list[str]
    created_at: str

    model_config = {"from_attributes": True}
