"""Pydantic schemas for interview coaching — guides and quality scoring."""

from pydantic import BaseModel, Field, field_validator

from discovery_engine.schemas.normalization import to_score_0_1, to_text


# ---------------------------------------------------------------------------
# Interview guide
# ---------------------------------------------------------------------------


class InterviewGuideRequest(BaseModel):
    """Input parameters for generating an interview guide."""

    hypothesis: str
    target_persona: str
    existing_insights: str = ""


class InterviewGuideExtracted(BaseModel):
    """An interview guide generated by the LLM."""

    title: str = ""
    opening_questions: list[dict] = []
    deep_dive_questions: list[dict] = []
    validation_questions: list[dict] = []
    anti_patterns_to_avoid: list[str] = []
    success_criteria: str = ""

    @field_validator("title", mode="before")
    @classmethod
    def _to_text_fields(cls, v):
        return to_text(v)

    @field_validator("success_criteria", mode="before")
    @classmethod
    def _success_criteria_to_text(cls, v):
        if isinstance(v, list):
            return "\n".join(str(item).strip() for item in v if item)
        return to_text(v)


class InterviewGuideResponse(BaseModel):
    """Persisted interview guide returned via the API."""

    id: str
    project_id: str
    title: str
    hypothesis: str = ""
    target_persona: str = ""
    opening_questions: list[dict]
    deep_dive_questions: list[dict]
    validation_questions: list[dict]
    anti_patterns_to_avoid: list[str]
    success_criteria: str
    created_at: str

    model_config = {"from_attributes": True}


# ---------------------------------------------------------------------------
# Quality scoring
# ---------------------------------------------------------------------------


class QualityScoreExtracted(BaseModel):
    """Quality assessment of an interview produced by the LLM."""

    overall_score: float = Field(default=0.0, ge=0.0, le=1.0)
    mom_test_compliance: float = Field(default=0.0, ge=0.0, le=1.0)
    question_quality: float = Field(default=0.0, ge=0.0, le=1.0)
    insight_depth: float = Field(default=0.0, ge=0.0, le=1.0)
    bias_score: float = Field(default=0.0, ge=0.0, le=1.0)
    leading_questions_found: list[dict] = []
    missed_opportunities: list[dict] = []
    strengths: list[str] = []
    suggestions: list[str] = []

    @field_validator(
        "overall_score",
        "mom_test_compliance",
        "question_quality",
        "insight_depth",
        "bias_score",
        mode="before",
    )
    @classmethod
    def _normalize_scores(cls, v):
        # Handle {"score": 0-100, "details": "..."} nested form from older prompt
        if isinstance(v, dict):
            v = v.get("score", 0)
        return to_score_0_1(v)


class QualityScoreResponse(BaseModel):
    """Persisted quality score returned via the API."""

    id: str
    interview_id: str
    overall_score: float
    mom_test_compliance: float
    question_quality: float
    insight_depth: float
    bias_score: float
    leading_questions_found: list[dict]
    missed_opportunities: list[dict]
    strengths: list[str]
    suggestions: list[str]
    created_at: str

    model_config = {"from_attributes": True}
